name: Tests & Vercel Deploy

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push: # действие и ветка в gh для запуска pipeline
    branches: [ "develop" ]

jobs:
  tests:
    name: Tests # название работы в нашем pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3 # клонируем репозиторий

      - name: Install dependencies
        run: yarn # устанавливаем зависимости

      - name: Run e2e tests
        run: yarn test:e2e # запускаем скрипт e2e тестов
        env:
          ENV: ${{ vars.ENV_GH }} # указываем необходимые переменные для тестов

  #  https://vercel.com/guides/how-can-i-use-github-actions-with-vercel
  deploy:
    name: Deploy # название работы в нашем pipeline
    needs: tests # указываем job после которой запустится текущая
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # clone repo
      - name: Install Vercel CLI
        run: npm install --global vercel@latest # install latest cli
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }} # pull token from production environment
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }} # build project
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }} # deploy project to vercel